version: "3.7"

services:

  reverseproxy:
    build:
      context: .
      dockerfile: Nginx.Dockerfile
    ports:
      - "80:80"
      - "443:443"
    restart: always

  api:
    depends_on:
      - reverseproxy
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "6000"
    restart: always